import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Index from '.'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ecommerce Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className }`}>
        <Index />
        </body>
    </html>
  )
}
